
import __ASTRO_IMAGE_IMPORT_Z1e9a7o from "./images/threejs-displacement/displacement-map.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearning-displacement-threejs.md";
import __ASTRO_IMAGE_IMPORT_Z1dXB1j from "./images/threejs-displacement/displaced-mesh.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearning-displacement-threejs.md";
import __ASTRO_IMAGE_IMPORT_ZEtLE6 from "./images/threejs-displacement/bricks-texture-map.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearning-displacement-threejs.md";
import __ASTRO_IMAGE_IMPORT_Z7WDgw from "./images/threejs-displacement/bricks-displacement-map.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearning-displacement-threejs.md";
import __ASTRO_IMAGE_IMPORT_Z24DXxT from "images/learning-theory-resp--brain-circuit.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearning-theory-response.md";
import __ASTRO_IMAGE_IMPORT_Z1LESTV from "./images/tjsj-019-aquarium.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthreejs-journey-challenge19-aquarium.md";
import __ASTRO_IMAGE_IMPORT_czYBH from "./images/tjsj-019-surreal-aquarium.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthreejs-journey-challenge19-aquarium.md";
import __ASTRO_IMAGE_IMPORT_ZPCQD6 from "./images/tjsj-020-cozy-thumbnails.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthreejs-journey-challenge20-cozy.md";
import __ASTRO_IMAGE_IMPORT_ZXnV9z from "./images/tjsj-020-first-room-chair.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthreejs-journey-challenge20-cozy.md";
import __ASTRO_IMAGE_IMPORT_1C65iF from "./images/tjsj-020-cozy-room-oct13.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthreejs-journey-challenge20-cozy.md";
import __ASTRO_IMAGE_IMPORT_2ibXTA from "./images/tjsj-020-cozy-final.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthreejs-journey-challenge20-cozy.md";
export default new Map([["./images/threejs-displacement/displacement-map.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearning-displacement-threejs.md", __ASTRO_IMAGE_IMPORT_Z1e9a7o], ["./images/threejs-displacement/displaced-mesh.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearning-displacement-threejs.md", __ASTRO_IMAGE_IMPORT_Z1dXB1j], ["./images/threejs-displacement/bricks-texture-map.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearning-displacement-threejs.md", __ASTRO_IMAGE_IMPORT_ZEtLE6], ["./images/threejs-displacement/bricks-displacement-map.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearning-displacement-threejs.md", __ASTRO_IMAGE_IMPORT_Z7WDgw], ["images/learning-theory-resp--brain-circuit.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Flearning-theory-response.md", __ASTRO_IMAGE_IMPORT_Z24DXxT], ["./images/tjsj-019-aquarium.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthreejs-journey-challenge19-aquarium.md", __ASTRO_IMAGE_IMPORT_Z1LESTV], ["./images/tjsj-019-surreal-aquarium.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthreejs-journey-challenge19-aquarium.md", __ASTRO_IMAGE_IMPORT_czYBH], ["./images/tjsj-020-cozy-thumbnails.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthreejs-journey-challenge20-cozy.md", __ASTRO_IMAGE_IMPORT_ZPCQD6], ["./images/tjsj-020-first-room-chair.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthreejs-journey-challenge20-cozy.md", __ASTRO_IMAGE_IMPORT_ZXnV9z], ["./images/tjsj-020-cozy-room-oct13.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthreejs-journey-challenge20-cozy.md", __ASTRO_IMAGE_IMPORT_1C65iF], ["./images/tjsj-020-cozy-final.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthreejs-journey-challenge20-cozy.md", __ASTRO_IMAGE_IMPORT_2ibXTA]]);
		